myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts.views import (
    main_page,
    about,
)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls",namespace="posts")),
    url(r'^about', about, name="about"),
    # url(r'^markdown/', include('django_markdown.urls')),
    url(r'^$', main_page, name="main"),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url, include
from posts.views import post_detail, post_list, post_create


urlpatterns = [
    url(r'^create/', post_create, name="create"),

    url(r'^$', post_list, name="list"),

    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),

]

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.shortcuts import reverse
from colorfield.fields import ColorField
from markdown_deux import markdown
from django.utils.safestring import mark_safe
User = get_user_model()

types = (
    ('a', 'programming'),
    ('b', 'personal'),
    ('c', 'Brain storming'),

)


def upload_location(instance, filename):
    if instance.id:
        new_id = instance.id
    else:
        new_id = Post.objects.order_by("id").last().id + 1
    return "%s/%s" % (new_id, filename)


# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, default=1, null=False)
    title = models.CharField(null=False, max_length=50)
    content = models.TextField(null=False, blank=False)
    # content = MarkdownField(null=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    slug = models.SlugField(unique=True)
    wait = models.BooleanField(default=False)
    color = ColorField(default='#FFFFFF')
    type = models.CharField(choices=types, max_length=3, default=1)
    image = models.ImageField(
        upload_to=upload_location,
        null=False, blank=False,
        height_field='height_field',
        width_field='width_field',

    )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)

    class Meta:
        ordering = ["-timestamp"]

    def __unicode__(self):
        return "%s:%s" % (self.user, self.title)

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={'slug': self.slug})

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from . models import Post
class PostForm(forms.ModelForm):
    """docstring for PostForm """

    class Meta:
        """docstring for Meta"""
        model = Post
        fields = [
            "title",
            "content",
            "wait",
            "color",
            "image",
            "type"
        ]

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import PostForm
from django.http import HttpResponseRedirect, Http404  # HttpResponse
from django.contrib import messages


# Create your views here.
def post_create(request):
    if not (request.user.is_staff or request.user.is_superuser):
        raise Http404
    if not request.user.is_authenticated():
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "item Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        messages.error(request, "Error enter data again")
    context = {
        "form": form,
    }
    return render(request, "form.html", context)


def main_page(request):
    query_list = Post.objects.filter(wait=False)[:3]
    context = {
        'posts': query_list,
    }
    return render(request, "index.html", context)


def post_list(request):
    query_list_posts = Post.objects.filter(wait=False)
    paginator = Paginator(query_list_posts, 3)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger or EmptyPage:
        contacts = paginator.page(1)
    context = {
        'contacts': contacts,
        # 'form': PostForm
    }
    return render(request, "list.html", context)


def about(request):
    return render(request, "about.html")


def post_detail(request, slug=None):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,

    }
    return render(request, "post.html", context)

templates/about.html
{% extends "index.html" %}
{% block title %}
    about me |{{ block.super }}
{% endblock %}
{% block content %}
    <header class="intro-header" style="background-image: url('media/img/testabout.png')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="row">
                    <div class="col-sm-7">
                        <ul>
                            <li>
                                <p>I am Amr Anwar -- 21 years old,
                                Passionate about coding specially anything related to the Web, always open to learn more.</p>
                            </li>
                            <li>
                                <p>I can develop Websites & APIs using Python Frameworks like Django</p>

                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-5">
                        <p><img class="img-responsive" src="{{ '/media/img/me.jpg' }}" alt="Chania">
                        </p>
                    </div>
                </div>
                <div class="row">
                 <ul>
                        <li> Some Of My Personal Projects using Django and Django Rest Api Framework as Backend,
                            the frontend by me using Bootstrap and Jquery
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="thumbnail">
                                <div class="caption">
                                    <a target="_blank" href="http://amranwar.pythonanywhere.com/"><h3 class="project-name">Simple SocialMedia</h3></a>
                                    <p>user can create posts and follow, like users posts and more </p>
                                    <a target="_blank" href="https://github.com/AmrAnwar/simple-SocialMedia" class="btn btn-primary" role="button">Code</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="thumbnail">
                                <div class="caption">
                                    <a target="_blank" href="#"><h3 class="project-name">ToDoList for Project Management</h3></a>

                                    <p>Trying to build website similar to taiga.io<br>
                                    Create list, lists have tasks each task has status, points, files, sublists & more </p>
                                    <a target="_blank" href="https://github.com/AmrAnwar/ToDoList_Django_Project" class="btn btn-primary" role="button">Code</a>
                                    <a target="_blank" href="https://github.com/AmrAnwar/ToDoList_Django_RestAPI_Project" class="btn btn-primary" role="button">Api Code</a>

                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="thumbnail">
                                <div class="caption">
                                    <h3>Ask site</h3>
                                    <p>Trying to build site like Ask.fm .</p>
                                    <a target="_blank" href="https://github.com/AmrAnwar/today-Ask-site" class="btn btn-primary" role="button">Code</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    </ul>
                    </div>

                <div class="row">
                <hr>
                    <div class="col-sm-11 col-sm-offset-1">
                        <ul>


                            <li>
                                <p><em>Want to work together? </em> <a href="mailto:amranwar945@gmail.com"> I’d like to
                                    hear
                                    from you. </a>
                                </p>
                            </li>
                            <a target="_blank"  href="https://docs.google.com/document/d/1DihpRFkhPU3y4EFr9EmN4s2YkhuFStOVxHEvP0jC8c8" class="project-name">
                            <li><i class="fa fa-file"></i>
                My Cv For More Technical Info About me

                            </li>
                            </a>
                            <br>
                            <li>
                                Contact Info:
                                <ul>
                                    <li>email : amranwar945@gmail.com</li>
                                    <li>phone: +974 3115 2704</li>
                                    <li>my social media accounts in the blog footer</li>
                                </ul>
                            </li>

                            <li>
                                <p>Apart from technology,I am interested in everything related to Japan and their culture
                                </p>

                            </li>
                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>

    <hr>
{% endblock %}

templates/contact.html
{% extends "index.html" %}

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('media/img/contact-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>

templates/form.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

<h1>ADD post</h1>
<!--default value if GET -->
{% block content %}
    <div class="col-sm-6 col-sm-offset-3">

    <h1>{{ title }}</h1>
    <br>
        {#{{ block.super }}#}
        <form method="POST" action="." enctype="multipart/form-data">{%csrf_token%}
        {{form|crispy}}
        <input type="submit" class="btn btn-default" value="submit">
        </form>
    </div>

{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
{% block header %}

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
{% endblock %}

        <title>
            {% block title %}
                AmrAnwar Blog
            {% endblock %}
        </title>

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Theme CSS -->
        <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
              type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
              rel='stylesheet' type='text/css'>
        <link rel="icon" href='/media/favicon.ico' type="image/x-icon">

    </head>
<body>
{% block navbar %}
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand"  href="{% url "main" %}">Amr Anwar</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url "main" %}">Home</a>
                    </li>

                    <li>
                        <a href="{% url "posts:list" %}">posts List</a>
                    </li>
                                        <li>
                        <a href="{% url "about" %}">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
{% endblock %}
{% block content %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/media/img/darksky.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>AmrAnwar Blog</h1>
                                                <span class="subheading">
                               Posts about things I love
                        </span>
                        <hr class="small">
                    </div>
                </div>
            </div>
        </div>
    </header>


    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for post in posts %}
                    <div class="post-preview">
                        <a href="{{ post.get_absolute_url }}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{ post.content|striptags|truncatechars:40 }}
                            </h3>
                        </a>
                        <p class="post-meta">Posted by {{ post.user }} since {{ post.timestamp|timesince }}</p>
                    </div>
                    <hr>

                {% endfor %}

                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="{% url 'posts:list' %}">Posts List &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="https://www.linkedin.com/in/amranwer/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/amranwar945">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/AmrAnwar">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                </ul>
                
            </div>
        </div>
    </div>
</footer>

<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Contact Form JavaScript -->
<script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
<script src="{% static 'js/contact_me.js' %}"></script>

<!-- Theme JavaScript -->
<script src="{% static 'js/clean-blog.min.js' %}"></script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="fb-root"></div>


<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

</body>

</html>

templates/list.html
{% extends "index.html" %}
            {% block title %}
                Posts List
            {% endblock %}
{% block content %}
        <header class="intro-header" style="background-image: url('http://amranwar00.pythonanywhere.com/media/img/bluesky.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Posts List</h1>
                        <hr class="small">
                        <span class="subheading">Hope You Find What you want.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for post in contacts %}
                    <div class="post-preview">

                        <a href="{{ post.get_absolute_url }}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{ post.content|striptags|truncatechars:40 }}
                            </h3>
                        </a>
                        <p class="post-meta">Posted by {{ post.user }} {{ post.timestamp|timesince }}</p>
                    </div>
                    <hr>

                {% endfor %}

            {% if contacts.has_other_pages %}
  <ul class="pagination">
    {% if contacts.has_previous %}
      <li><a href="?page={{ contacts.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in contacts.paginator.page_range %}
      {% if contacts.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if contacts.has_next %}
      <li><a href="?page={{ contacts.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

            </div>


        </div>
    </div>

{% endblock %}

templates/post.html
{% extends "index.html" %}
{% block header %}

    {{ block.super }}


{% endblock %}
{% block title %}
    {{ post.title }}|{{ block.super }}
{% endblock %}
{% block content %}

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('http://amranwar00.pythonanywhere.com/{{ post.image.url }}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading" style="color: {{ post.color }}">
                        <h1>{{ post.title }}</h1>
                        <h2 class="subheading">{{ post.content|striptags|truncatechars:40 }}</h2>
                        <span class="meta">Posted by <a
                                href="{% url 'about' %}">{{ post.user }}</a> {{ post.timestamp }}</span>

                        <span>
<div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button"data-mobile-iframe="true">

  </div>


                    <!--                                                <div class="fb-share-button" data-href="{{ request.build_absolute_uri }}" data-layout="button"-->
                    <!-- ><a class="fb-xfbml-parse-ignore" target="_blank"-->
                    <!--                                                    href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2F127.0.0.1%3A8000%2Fposts%2Ftest%2F&amp;src=sdkpreparse">Share</a>-->
                    <!--</div>-->

                            <div>
                                                                                <a href="https://twitter.com/home?status={{ post.content|truncatechars:80 }}%20{{ request.build_absolute_uri }}"
                       class="twitter-share-button"  data-show-count="false">Tweet</a>


                            </div>

                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">

                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

  <img src="{{ post.image.url }}" style="display:none" >
  <p style="display:none">{{ post.content|striptags|truncatechars:200 }}</p>
  {{ post.content|safe }}
                                    <br>
                <hr>

                                    <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="3"></div>

                </div>

            </div>


        </div>


        </div>
    </article>


    <hr>
{% endblock %}